camel:
  springboot:
    main-run-controller: true
  routes:
    realtime-auth:
      from: 'aws-s3://census-toy?amazonS3Client=#amazonS3Client&delay=5000&maxMessagesPerPoll=1&deleteAfterRead=false&prefix=kinesis-test'
      parallel: false
      to:
        - 'log:hello'
        - 'aws-kinesis://census-stream?amazonKinesisClient=#kinesisClient'
    kinesis-consumer:
      from: 'aws-kinesis://census-stream?amazonKinesisClient=#kinesisClient'
      parallel: false
      to:
#       - 'log:${body}'
        - 'log: message consumed'
aws:
  region: 'us-east-1'



     
        
