camel:
  springboot:
    main-run-controller: true
  routes:
    realtime-auth:
      from: 'timer://foo?fixedRate=true&period=30000'
      parallel: false
      to:
        - 'log:hello'
        - 'aws-kinesis://census-stream?amazonKinesisClient=#kinesisClient'    
aws:
<<<<<<< HEAD
  kinesis:
    region: 'us-east-1'
    accessKey:
    secretKey:
=======
  region: 'us-east-1'
  accessKey: 
  secretKey: 
    
>>>>>>> master
  
     
        
