camel:
  springboot:
    main-run-controller: true
  routes:
    realtime-auth:
      from: 'timer://foo?fixedRate=true&period=60000'
      parallel: false
      to:
        - 'log:hello'
        - 'log:world'
---
spring:
  profiles: kinesis
aws:
  kinesis:
    url: http://blah.com
    port: 8080
    region: US East
    accessKey: blah
    secretKey: blah
camel:
  routes:
    realtime-auth:
      from: 'timer://foo?fixedRate=true&period=30000'
      to:
        - 'log:hello'
        - 'log:world'    
     
        
