camel:
  springboot:
    main-run-controller: true
  routes:
    realtime-auth:
      from: 'timer://foo?fixedRate=true&period=30000'
      parallel: false
      to:
        - 'log:hello'
        - 'aws-kinesis://census-stream?amazonKinesisClient=#kinesisClient'    
aws:
  kinesis:
    region: 'us-east-1'
    accessKey: AKIAJICVN77U3A5PNPSA
    secretKey: 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
  
     
        
